#include <stdio.h>#include <stdlib.h>#include <string.h>
#define BLOCK_SIZE 8
#define ENCRYPT_ECB_MODE 1#define ENCRYPT_CBC_MODE 2#define DECRYPT_ECB_MODE 3#define DECRYPT_CBC_MODE 4 
#define ENCRYPT "encrypt"#define DECRYPT "decrypt"#define ECB "ecb"#define CBC "cbc"
#define MY_KEY "1dqbfj4hgnr66534kjgrfs"
void encryptECB(const char * inFileName, const char * outFileName);
/* * Execution format: * ./blowfish encrypt/decrypt ecb/cbc inFileName outFileName */int main(int argc, char * argv[]){       // initializing testing values:    argv[0] = "main";    argv[1] = "encrypt";    argv[2] = "ecb";    argv[3] = "myfile.txt";    argv[4] = "outfile.txt";    int k;    for (k=0; k<5; k++) {        printf("%s\n", argv[k]);       }    // end of testing initialization        // program arguments validation    if (argv[1] == NULL || argv[2] == NULL || argv[3] == NULL || argv[4] == NULL) {        printf("Upss, something is wrong, check your parameters!\n");         printf("Correct format: encrypt/decrypt ecb/cbc inFileName outFileName\n");         return 1;     }        // choose correct mode for encryption/decryption    int mode;    if (strcmp(argv[1], ENCRYPT) == 0) {        if (strcmp(argv[2], ECB) == 0) {            mode = ENCRYPT_ECB_MODE;        } else if (strcmp(argv[2], CBC) == 0) {            mode = ENCRYPT_CBC_MODE;        }    } else if (strcmp(argv[1], DECRYPT) == 0) {        if (strcmp(argv[2], ECB) == 0) {            mode = DECRYPT_ECB_MODE;        } else if (strcmp(argv[2], CBC) == 0) {            mode = DECRYPT_CBC_MODE;        }    }        char * inFile = argv[3];    char * outFile = argv[4];        // fire encryption/decryption in choosen mode    if (mode == ENCRYPT_ECB_MODE) {        printf("Start encrypting in ECB mode...\n");        encryptECB(inFile, outFile);        return 0;    }        if (mode == ENCRYPT_CBC_MODE) {        printf("Start encrypting in CBC mode...\n");        // encrypt(inFile, outFile);        return 0;    }        if (mode == DECRYPT_ECB_MODE) {        printf("Start decrypting in ECB mode...\n");        // encrypt(inFile, outFile);        return 0;    }        if (mode == DECRYPT_CBC_MODE) {        printf("Start decrypting in CBC mode...\n");        // encrypt(inFile, outFile);        return 0;    }        return 0;}
void encryptECB(const char * inFileName, const char * outFileName) {    // BF_KEY key;    FILE * inFile;    FILE * outFile;    unsigned char inBuffer[BLOCK_SIZE];    unsigned char outBuffer[BLOCK_SIZE];    int readBytes;
    if ((inFile = fopen(inFileName, "rb")) == NULL){        printf("Open file error occurred");        exit(1);    }
    // set key before encryption    // BF_set_key(&key, strlen(MY_KEY), MY_KEY);
    while (1) {        // reset buffer        memset(inBuffer, 0, BLOCK_SIZE);                // read 8 bytes of data in each loop        if ((readBytes = fread(inBuffer, 1, 8, inFile)) == -1) {            printf("Read error occurred");        }                 // end of file        if (readBytes == 0) {            break;        }                // apply padding if needed        if (readBytes < BLOCK_SIZE) {            printf("number of bytes red: %i", readBytes);            int padding = BLOCK_SIZE - readBytes;            printf(" -> padding aplied: %i\n", padding);            readBytes = readBytes + padding;        }                // do encryption        // BF_ecb_encrypt(inBuffer, outBuffer, &key, BF_ENCRYPT);                // save decrypted part of file                        printf("number of bytes red: %i\n", readBytes);    }
    fclose(inFile);}
